### ISSUE TITLE
In the Transaction History screen, Block Explorer links are not working.

### ISSUE THREAD

**Issue by coiki** [symbol/mobile-wallet#217] opened 2021-08-02 01:04 UTC
![image](https://user-images.githubusercontent.com/620159/127791604-b4b87f50-31d9-42ad-bf6a-b82c58bd3be8.png)

**Defect description**

Users looking at a past transaction click on the Block Explorer link, but it doesn't open anything at all.

**Expected Result**

When tapping on the Block Explorer link, the transaction I'm looking at should open in the block explorer website.

**Steps to Reproduce**

Pre-req: Make a transaction
1. Go to the detail of a past transaction,
2. Click on the link for the Block Explorer, at the bottom.
(bug) 3.  Nothing happens

**Affected Versions, OS, Device**

+ wallet latest version
+ Android 11
+ Sony Xperia 5
+ Samsung S21 Ultra

**Relevant Links**
https://twitter.com/sayosayo712/status/1421027940112822276
sayoさん、バグを教えてくれてありがとうございます！

**Comment by cryptoBeliever** [comment] 2021-08-02 05:09
Duplicate of: https://github.com/symbol/mobile-wallet/issues/214

**Closed by cryptoBeliever** 2021-08-02 05:09 UTC
