### ISSUE TITLE
While downloading paper wallet, getting error - Android mobile (P2)

### ISSUE THREAD

**Issue by surekabpm** [symbol/mobile-wallet#145] opened 2021-03-11 13:31 UTC
While creating a profile in the android mobile , i'm getting error when I download the paper wallet .can you please check
  @AdriaCarrera 
![image](https://user-images.githubusercontent.com/49143210/110794792-2019c180-829c-11eb-8fcb-6f5f823dc2e0.png)

**Comment by OlegMakarenko** [comment] 2021-03-17 21:26
Same on my side

**Comment by surekabpm** [comment] 2021-04-09 06:27
This issue is still not fixed .. i'm still getting "error saving file" when i click the download paper wallet

**Comment by surekabpm** [comment] 2021-04-15 05:18
I'm getting permission denied on the latest build , please have a look 
![image](https://user-images.githubusercontent.com/49143210/114817714-2689e480-9dd8-11eb-8580-7ba37cd0cc25.png)

**Comment by cryptoBeliever** [comment] 2021-07-13 21:23
@surekabpm it works for me. Could you check on your phone?

**Comment by surekabpm** [comment] 2021-07-20 05:33
Hi , It is still failing in my phone..looks like it is not fixed.. kindly check

**Comment by coiki** [comment] 2021-09-27 08:27
@surekabpm can you confirm if it works?

**Comment by surekabpm** [comment] 2021-10-05 08:40
@coiki I have tested against the new build and this issue is still there.

**Comment by cryptoBeliever** [comment] 2022-01-26 23:51
@OlegMakarenko I was able to reproduce this on my second phone (Honor 20 Pro). When I build APK with this flag -> https://github.com/joltup/rn-fetch-blob/issues/508#issuecomment-583455929 problem is solved.

**Comment by OlegMakarenko** [comment] 2022-01-28 10:45
Fixed, Merged into `main`.

**Closed by OlegMakarenko** 2022-01-28 10:45 UTC
Labels: P2 Issue, Needs Reproduction
